# FROM node:8-alpine

# RUN apt-get update && apt-get -y install bluetooth bluez libbluetooth-dev libudev-dev

# WORKDIR /app/

# COPY package*.json ./

# RUN npm install --production

# COPY app.js ./

# USER node

# CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
