# builder
FROM arm32v7/node:8-stretch as builder

WORKDIR /build/
COPY package*.json ./
RUN npm install --production
COPY *.js ./

# runtime 
FROM arm32v7/node:8-slim 

# requirements
RUN apt-get update && apt-get -y install bluetooth bluez libbluetooth-dev libudev-dev

# node can bluetooth
RUN setcap cap_net_raw+ep /usr/local/bin/node

WORKDIR /app/

# copy the app from the build container
COPY --from=builder /build/ .

USER node
CMD ["node", "app.js"]